import { Component } from '@angular/core';
// Import the main dashboard component to make it available
import { WorkerFlightsDashboardComponent } from './features/worker-flights-dashboard/components/worker-flights-dashboard/worker-flights-dashboard.component'; // Adjust path if needed

@Component({
  selector: 'app-root', // Default selector for the root component
  standalone: true, // Mark as standalone
  imports: [
    // Import necessary standalone components/modules here
    WorkerFlightsDashboardComponent, // Import the main dashboard component
  ],
  templateUrl: './app.component.html', // Link to the HTML template
  styleUrls: ['./app.component.scss'], // Link to the SCSS styles
})
export class AppComponent {
  // The title property is often generated by default but not strictly needed here
  title = 'worker-flights-app';
}
